#!/bin/bash

# verify an argument was provided
if [[ "$#" != 2 ]]; then
    echo "Wrong number of argument provided"
    exit 1
fi

ROOT_DIR=$(realpath "$2")
FILE_TYPE="$1"

while IFS= read -r -d '' file
do
  
    # transcode the file
    ffmpeg -hide_banner -nostdin -i "$file" -vcodec h264_nvenc -acodec copy -crf 28 "${file%.ts}.mp4" && \
    rm "$file"

done <   <(find "$ROOT_DIR" -name "*$FILE_TYPE" -print0)
